### ISSUE TITLE
Can't get the launcher to boot

### ISSUE THREAD

**Issue by steameddabs** [neatodev/BmLauncher#18]
Just installed by dragging and dropping to my binaries folder and now I can't get the launcher to boot through steam or my desktop. Wondering if I missed something in the installation process?

**Comment by steameddabs** [comment]
Attaching my log to see if that helps with solving the problem

[bmlauncher_report__04-04-22__04-15-24.log](https://github.com/neatodev/BmLauncher/files/8413206/bmlauncher_report__04-04-22__04-15-24.log)

**Comment by neatodev** [comment]
So the logging stops right before NVAPI gets initialized. Are your Nvidia drivers up to date?

**Comment by steameddabs** [comment]
Yes they're up to date.

**Comment by neatodev** [comment]
There is a new launcher update with some new features. Please give it a try and see if that works.

**Comment by Audioboxer** [comment]
New launcher isn't loading for me either, a previous one was working fine (can't remember what version it was, I copied over it).

Log

[bmlauncher_report__10-04-22__08-39-48.log](https://github.com/neatodev/BmLauncher/files/8458519/bmlauncher_report__10-04-22__08-39-48.log)

Last time I booted the game I had a 2080Ti, now I have a 3080.

**Comment by neatodev** [comment]
Did you follow the readme and delete old files?

**Comment by DukeNukem-1** [comment]
I also have problems with the launcher, I started from a new installation, the solution is to use the old version of the launcher as suggested.

**Comment by Audioboxer** [comment]
> Did you follow the readme and delete old files?

Thank you, I'm an idiot. To be fair it's the first time I've updated the launcher!

**Comment by nick1223344** [comment]
> I also have problems with the launcher, I started from a new installation, the solution is to use the old version of the launcher as suggested.

Is there a way to get an older version of the launcher? I also have the same issue with starting the latest, 1.6.2. launcher.

**Comment by DukeNukem-1** [comment]
@nick1223344   Try this one, it works for me.

[BmLauncher.zip](https://github.com/neatodev/BmLauncher/files/8459881/BmLauncher.zip)

**Comment by neatodev** [comment]
Could you please link log files (if possible)? For the time being, @DukeNukem-1 s solution is acceptable, preferably I'd like to solve this issue though.

**Comment by nick1223344** [comment]
> @nick1223344 Try this one, it works for me.
> 
> [BmLauncher.zip](https://github.com/neatodev/BmLauncher/files/8459881/BmLauncher.zip)

Yup. It works for me too. Thanks :D

**Comment by neatodev** [comment]
@nick1223344 @DukeNukem-1 @steameddabs I would like to thoroughly troubleshoot this with you if you'd like. Add me on Discord please: -------

The newer Launcher version offers improvements and fixes across the board and I would really like if it worked for everyone.

**Comment by nick1223344** [comment]
> Could you please link log files (if possible)? For the time being, @DukeNukem-1 s solution is acceptable, preferably I'd like to solve this issue though.

Sure if you can point me on how to do it. I only just created an account and I am not familiar with how GitHub works.

**Comment by DukeNukem-1** [comment]
@neatodev The first log is with the latest launcher and the second is with the old one.
[NEW_bmlauncher_report__10-04-22__10-03-55.log](https://github.com/neatodev/BmLauncher/files/8459896/NEW_bmlauncher_report__10-04-22__10-03-55.log)

[OLD_bmlauncher_report__10-04-22__10-12-33.log](https://github.com/neatodev/BmLauncher/files/8459895/OLD_bmlauncher_report__10-04-22__10-12-33.log)

**Comment by neatodev** [comment]
I might have a working version sorted. Would need one of you guys to test it for me. My Discord info is in my previous comment on this issue.

**Comment by nick1223344** [comment]
Here it go:
[NEW_bmlauncher_report__10-04-22__11-00-12.log](https://github.com/neatodev/BmLauncher/files/8459900/NEW_bmlauncher_report__10-04-22__11-00-12.log)
[OLD_bmlauncher_report__10-04-22__11-00-38.log](https://github.com/neatodev/BmLauncher/files/8459901/OLD_bmlauncher_report__10-04-22__11-00-38.log)

**Comment by neatodev** [comment]
Thanks to @DukeNukem-1 for troubleshooting with this. The [newest release](https://github.com/neatodev/BmLauncher/releases/tag/1.6.3), specifically https://github.com/neatodev/BmLauncher/commit/56f58451bca6f8628282c26aaac1f4f2728639d3 should fix this issue entirely.
