### ISSUE TITLE
Launcher not detecting correct GPU

### ISSUE THREAD

**Issue by Vandal101** [neatodev/BmLauncher#2]
The launcher does not detect the dedicated GPU in my laptop, even if I set it to use my Nvidia GPU in the control panel it still detects my Intel integrated GPU, because of this I cant enable HBAO+.

![Untitled4](https://user-images.githubusercontent.com/50757099/85227483-369d8700-b3b4-11ea-8a96-570332ab352f.png)

**Comment by neatodev** [comment]
Please add me on Discord, Neato#7128. I would like to troubleshoot this with you.

**Comment by neatodev** [comment]
Fixed issue in latest commit. Thanks for bringing it to my attention.
