### ISSUE TITLE
Also can't get launcher to boot

### ISSUE THREAD

**Issue by MagmaLeCreme** [neatodev/BmLauncher#20]
This is the first time I've installed this, but after doing everything in the readme the game just won't use the launcher. It just uses the default launcher every time.

**Comment by neatodev** [comment]
That means you have placed the launcher in the wrong folder. Make sure you place it in the BINARIES folder.

**Comment by MagmaLeCreme** [comment]
Sorry I'm a fucking idiot, I put it in the binaries of the epic games folder and not the binaries folder in my documents. Thanks for the fast response though man.
