### ISSUE TITLE
[Feature Request] Add options for Mouse Sensetivity and Smoothing

### ISSUE THREAD

**Issue by abi-21** [neatodev/BmLauncher#22]
I know it's easy just to edit them in documents but it would be nice to have these options inside launcher.

**Comment by neatodev** [comment]
I will look into this. Thanks for the suggestion!

**Comment by neatodev** [comment]
I've implemented this feature. Please download the [newest release](https://github.com/neatodev/BmLauncher/releases/latest).

Specific commit: https://github.com/neatodev/BmLauncher/commit/0e429d91cdea7f894151e180d823058a2b623d89
