### ISSUE TITLE
Launcher seems to crash when trying to pull GPU information

### ISSUE THREAD

**Issue by ShadowFlame365** [neatodev/BmLauncher#23]
Launcher attempts to load and seems to throw an exception when trying to pull GPU information during initialization. Attached is the log file and also the log with the exception from Event Viewer:
[bmlauncher_report__03-06-22__08-26-11.log](https://github.com/neatodev/BmLauncher/files/8836289/bmlauncher_report__03-06-22__08-26-11.log)
[eventlog_bmlauncher.txt](https://github.com/neatodev/BmLauncher/files/8836290/eventlog_bmlauncher.txt)

Card is a GTX 1080, drivers are the latest Nvidia drivers (512.95).
I tried on my laptop which has an AMD card and it does seem to work fine, possibly an issue exclusive to Nvidia?

**Comment by neatodev** [comment]
Do you get any kind of error that pops up on screen or does nothing happen at all?

**Comment by ShadowFlame365** [comment]
No error message or any other kind of pop up at all, it just attempts to load for half a second then nothing else happens. I only found the log from Event Viewer by taking a shot in the dark.

Also just did a full DDU and reinstall of graphics driver with no change.

Interestingly, I fully reinstalled the game to try and see if the stock launcher worked, and it seems to pull a similar error message, so now I'm not sure the Advanced Launcher is at fault:
![stock_bmlauncher_error](https://user-images.githubusercontent.com/5157049/172065315-662cbaf3-1f42-4bc7-88c6-1f5ab9c483e2.png)

**Comment by neatodev** [comment]
I looked for possible solutions for this error and came across [this](https://social.technet.microsoft.com/forums/ie/en-US/fcf1153b-edb2-4377-adc0-cfd99f52227c/windows-2008r2-cannot-add-server-role-systemruntimeinteropservicescomexception-0x80070422?forum=winservergen).

Open CMD as admin and run:
`sfc /scannow`

See if this helps.

**Comment by ShadowFlame365** [comment]
No dice there either:
![sfc_github](https://user-images.githubusercontent.com/5157049/172066365-a04c0c4b-85f9-468a-a9a4-2a0e84e17d90.png)

**Comment by neatodev** [comment]
Please make sure that .NET Framework is enabled on your system (I'm gonna assume you have it installed, otherwise you should get a different error)

```
Hit Win + S
Search "Windows Features"
Open "Turn Windows features on or off"
```
Now make sure that .NET Framework 3.5 & 4.8 are checked.

EDIT:
Apparently this error also occurs when you have the Windows Update Service disabled, so that could also be the cause.

**Comment by ShadowFlame365** [comment]
Both are set as enabled:
![features_github](https://user-images.githubusercontent.com/5157049/172066633-859d0d2e-1cd4-4c72-adc1-c6a9beda847d.png)

I unchecked and rechecked both of them so they could reinstall with no change (I don't think it's otherwise possible to fully uninstall .NET 4.8 in Windows 10/11 since it seems to be baked into the OS.)

Both Windows Update services were enabled but not running, I started both of them but no change there either:
![image](https://user-images.githubusercontent.com/5157049/172066758-3a2f6563-1f64-443b-aab7-1800ec5325a9.png)

**Comment by neatodev** [comment]
You could also try the [.NET Framework Repair Tool](https://www.microsoft.com/en-us/download/details.aspx?id=30135).

If that won't do it, you can try running CMD as admin again and executing the following command:
`Dism.exe /online /enable-feature /featurename:NetFX3 /source:C:\ /LimitAccess`

EDIT:
If it doesn't happen automatically, you should definitely reboot your PC after the repair.

**Comment by ShadowFlame365** [comment]
No luck for either, even after rebooting:
![image](https://user-images.githubusercontent.com/5157049/172067181-77b4d3c0-8c56-4a27-a3d2-a7631c3b0b3b.png)

**Comment by neatodev** [comment]
Another attempt with DISM would be the following:

Open CMD as admin, then execute these two commands in order:

```
1) DISM /Online /Cleanup-Image /CheckHealth

2) DISM.exe /Online /Cleanup-image /Restorehealth
```

**Comment by ShadowFlame365** [comment]
No change either:
![image](https://user-images.githubusercontent.com/5157049/172067534-78850834-384b-4d63-965b-84136e009e20.png)

**Comment by neatodev** [comment]
Sorry, but I don't know of any other possible fix. Since this also occurs with the default launcher it's not an issue caused by the Advanced Launcher. All I know is that, like the Advanced Launcher, the default launcher runs via .NET Framework so this is (almost) certainly a .NET issue. To what extent, I don't know, sorry.

I'm gonna keep this issue open and hope you will share your solution here, should you find one.

Best of luck.

**Comment by neatodev** [comment]
Alright, just one more possible solution because I just looked at your eventviewer logfile.

Your WMI (Windows Management Instrumentation) might be broken.

To figure out if it is indeed broken, you need to do the following ([source](https://stackoverflow.com/a/66690753)):
```
1) Start-->Run-->Wmimgmt.msc and press enter
2) In the left most pane of the window that opens, Right click on WMI Control(local) and select properties.
3) If the properties windows displays any error message, it confirms that WMI is broken on windows.
```

If it is broken, click [this link](https://www.thewindowsclub.com/how-to-repair-or-rebuild-the-wmi-repository-on-windows-10) to repair it.

**Comment by ShadowFlame365** [comment]
You are an absolute genius.

I have no idea how this happened, but the WMI service was set as Disabled which perfectly explains the error message. I set it to Automatic, then reset the repository in Command Prompt and now everything works perfectly, both the stock launcher and the Advanced Launcher:

![image](https://user-images.githubusercontent.com/5157049/172071094-5bd15e20-9925-4e1f-88b1-de0e68a3f53f.png)


Was preparing to completely reinstall Windows at this point, so I greatly appreciate your efforts.

**Comment by neatodev** [comment]
I'm glad we managed to fix it :)
