### ISSUE TITLE
Update to .net 6 or 7 and compile as standalone

### ISSUE THREAD

**Issue by beyondmeat** [neatodev/BmLauncher#25]
.net framework is dead, long live .net

Compiling as framework-independent removes the requirement of needing .net installed.

Either way update to .net 6 or 7 please, it's much better than old framework and should be easy to do.

**Comment by neatodev** [comment]
Hey, thanks for your recommendation but I will not be doing this for the following reasons:

- .NET Framework 4.8 is pre-installed on every Windows OS starting with Windows 7 SP1.
- .NET 6 has dodgy Wine/Proton support. I'm currently writing the city version of the launcher in .NET 6 and I've learned this the hard way. With the upgrade to .NET 6 I would essentially be preventing that subset of users to use the launcher.
- The framework-independent binary would be a couple hundred MB big and also run slower.

**Comment by beyondmeat** [comment]
4.8 does not come with win7 nor win10. 
Win7 came with 3.5 or maybe 4.0 and won't run a 4.8 app without the 4.8 framework.
Windows update may install it on 7 but doubtful without the optional Microsoft updates enabled in the WU settings.


It is included in Win11. 

.net6 Linux users can use the cli if you refactor and provide cli support. If they must have a gui then consider using a asp.net based UI, which would be cross platform. Eventually MAUI will get Linux support. 

.net6 is faster and compiling standalone isn't slower either.

The only issue is wine/proton which can be solved by using a web ui or adding cli support then it won't need wine/proton since .net6 is linux native in the cli. Try that for the city launcher.

**Comment by neatodev** [comment]
I'm not adding CLI or web support. If people want to look into that they are free to fork the repo and write it themselves.
The launcher has been tested on completely fresh installs of every OS listed in the readme file by myself and others and could be run without needing to separately download .net framework 4.8. So the required dependencies do in fact come pre-installed.
