### ISSUE TITLE
Exclamation noise heard, app closes

### ISSUE THREAD

**Issue by Sleazus** [neatodev/BmLauncher#4]
When I try to run BmLauncher, I hear an alert sound, Very similar to the noise when guards catch you in Metal Gear Solid, then it just closes

**Comment by Sleazus** [comment]
Ok, Sorry, I checked the crash logs and i had dxgi.dll in there for some reason.
Renaming that fixed the issue

**Comment by neatodev** [comment]
Alright then, glad you sorted it out.
