### ISSUE TITLE
General protection fault, can't play game

### ISSUE THREAD

**Issue by pixarfan2003** [neatodev/BmLauncher#5]
Hey there! I previously used this launcher with the Epic Games version of the game, but I recently got it for Steam so I had to add the installer again. I've set all the settings within the launcher as I'd like, but when I click "Start Game," I get a dialog box that reads:

"General protection fault!

History: QA_APPROVED_BUILD_OCTOBER_2008 198408 23-01-2010 21:41.02 FMOD: 42200/42200 Game

RaiseException() Address = 0x75a0a892 (filename not found) [in C:\WINDOWS\System32\KERNELBASE.dll]

GColor::GetHSI() Address = 0x1bf8f1d  (filename not found) [in C:\Program Files (x86)\Steam\steamapps\common\Batman Arkham Asylum GOTY\Binaries\ShippingPC-BmGame.exe]

GColor::GetHSI() Address = 0x1a38cdd  (filename not found) [in C:\Program Files (x86)\Steam\steamapps\common\Batman Arkham Asylum GOTY\Binaries\ShippingPC-BmGame.exe]

GImage::GImage() Address = 0xa40bdc   (filename not found) [in C:\Program Files (x86)\Steam\steamapps\common\Batman Arkham Asylum GOTY\Binaries\ShippingPC-BmGame.exe]

GetStackOwnerClass() Address = 0x1503d1f  (filename not found) [in C:\Program Files (x86)\Steam\steamapps\common\Batman Arkham Asylum GOTY\Binaries\ShippingPC-BmGame.exe]

GetOutermost() Address = 0x5f02ac   (filename not found) [in C:\Program Files (x86)\Steam\steamapps\common\Batman Arkham Asylum GOTY\Binaries\ShippingPC-BmGame.exe]

GetStackOwnerClass() Address = 0x150a32e  (filename not found) [in C:\Program Files (x86)\Steam\steamapps\common\Batman Arkham Asylum GOTY\Binaries\ShippingPC-BmGame.exe]"

If I click the OK button, the game never launches. How do I fix this?

**Comment by neatodev** [comment]
Doesn't look like a launcher issue. Try fixing the problems with one of these solutions:
https://steamcommunity.com/app/35140/discussions/0/611703898451324537/
https://steamcommunity.com/app/35140/discussions/0/792924412066344489/

**Comment by pixarfan2003** [comment]
Awesome, thanks for those. Sorry to bother you about it.

**Comment by pixarfan2003** [comment]
Awesome, thanks for those. Sorry to bother you about it.
